[package]
name = "spel-katalog-sink"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
derive_more = { workspace = true, features = ["display"] }
flume.workspace = true

[lints]
workspace = true
