disallowed-types = [
	"std::sync::mpsc::Sender",
	"std::sync::mpsc::Receiver",
	"tokio::sync::mpsc::Sender",
	"tokio::sync::mpsc::Receiver",
	"tokio::sync::mpsc::UnboundedSender",
	"tokio::sync::mpsc::UnboundedReceiver",
	"futures::channel::mpsc::Sender",
	"futures::channel::mpsc::Receiver",
	"futures::channel::mpsc::UnboundedSender",
	"futures::channel::mpsc::UnboundedReceiver",
	"iced::futures::channel::mpsc::Sender",
	"iced::futures::channel::mpsc::Receiver",
	"iced::futures::channel::mpsc::UnboundedSender",
	"iced::futures::channel::mpsc::UnboundedReceiver",
	"tokio::task::JoinError",
	"tokio::process::Command",
]
disallowed-methods = [
	"std::sync::mpsc::channel",
	"tokio::sync::mpsc::channel",
	"tokio::sync::mpsc::unbounded_channel",
	"futures::channel::mpsc::channel",
	"futures::channel::mpsc::unbounded",
	"iced::futures::channel::mpsc::channel",
	"iced::futures::channel::mpsc::unbounded",
	"tokio::task::spawn_blocking",
	"tokio::time::sleep",
	"tokio::fs::create_dir_all",
	"tokio::fs::try_exists",
	"tokio::fs::read_to_string",
	"tokio::fs::write",
	"tokio::fs::read",
	"tokio::fs::copy",
	"tokio::fs::remove_file",
	"tokio::fs::read_dir",
	"tokio::sync::oneshot::channel",
	"tokio::process::Command::new",
	{ path = "spel_katalog_common::w::scroll", replacement = "spel_katalog_widget::scrollable" },
	{ path = "iced_widget::rule::horizontal", replacement = "spel_katalog_widget::rule::horizontal" },
	{ path = "iced_widget::rule::vertical", replacement = "spel_katalog_widget::rule::vertical" },
	{ path = "iced_widget::scrollable", replacement = "spel_katalog_widget::scrollable" },
	{ path = "iced::widget::rule::horizontal", replacement = "spel_katalog_widget::rule::horizontal" },
	{ path = "iced::widget::rule::vertical", replacement = "spel_katalog_widget::rule::vertical" },
	{ path = "iced::widget::scrollable", replacement = "spel_katalog_widget::scrollable" },
]
